# Generated by Django 4.2.7 on 2025-04-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("typing_game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lyricsnippet",
            name="yt_url",
            field=models.URLField(
                blank=True,
                help_text="Optional: Full YouTube video URL (e.g., https://www.youtube.com/watch?v=...)",
                max_length=255,
                null=True,
            ),
        ),
    ]
