# Generated by Django 4.2.7 on 2025-04-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("typing_game", "0002_lyricsnippet_yt_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lyricsnippet",
            name="yt_url",
        ),
        migrations.AddField(
            model_name="lyricsnippet",
            name="yt_id",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
