# Generated by Django 4.2.7 on 2025-04-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("typing_game", "0003_remove_lyricsnippet_yt_url_lyricsnippet_yt_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lyricsnippet",
            name="yt_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
